home:
  - changed-files:
      - any-glob-to-any-file: "app/(home)/**"

post:
  - changed-files:
      - any-glob-to-any-file: "app/post/**"

category:
  - changed-files:
      - any-glob-to-any-file: "app/(category)/**"

dock:
  - changed-files:
      - any-glob-to-any-file: "components/dock/**"

pagination:
  - changed-files:
      - any-glob-to-any-file: "components/pagination/**"

widget:
  - changed-files:
      - any-glob-to-any-file: "components/widgets/**"

series:
  - changed-files:
      - any-glob-to-any-file: "components/series/**"

comments:
  - changed-files:
      - any-glob-to-any-file: "components/comments/**"

storybook:
  - changed-files:
      - any-glob-to-any-file: "stories/**"

infra:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

util:
  - changed-files:
      - any-glob-to-any-file: "lib/**"
