- name: feat
  color: "1d76db"
  description: New feature
- name: chore
  color: "cccccc"
  description: Chore / infra
- name: test
  color: "0e8a16"
  description: Testing
- name: a11y
  color: "5319e7"
  description: Accessibility
- name: home
  color: "0052cc"
  description: Home page
- name: post
  color: "fbca04"
  description: Post detail
- name: category
  color: "d93f0b"
  description: Category page
- name: dock
  color: "5319e7"
  description: DockMenu
- name: comments
  color: "0366d6"
  description: Giscus / Comments
- name: widget
  color: "0b7285"
  description: Widgets / metrics
- name: series
  color: "a2eeef"
  description: Series
- name: pagination
  color: "7057ff"
  description: Pagination
- name: util
  color: "6f42c1"
  description: Utils / helpers
- name: infra
  color: "24292e"
  description: Infra / CI
- name: storybook
  color: "ededed"
  description: Storybook
