reviews:
  auto_review:
    enabled: true
  profile: assertive

path_filters:
  exclude:
    - "**/*.md"
    - "**/*.stories.*"
    - "**/dist/**"
    - "**/.next/**"

comments:
  language: ko
  tone: friendly
