name: π”§ DevOps/CI
description: CI/CD λ° μΈν”„λΌ κ΄€λ ¨ μ‘μ—… ν…ν”λ¦Ώ
title: "infra: [μ‘μ—…λ…]"
labels: ["infra"]
body:
  - type: textarea
    id: desc
    attributes:
      label: μ‘μ—… μ„¤λ…
      placeholder: "μ: GitHub Actions ν…μ¤νΈ μλ™ μ‹¤ν–‰ μ„¤μ •"

  - type: checkboxes
    id: checklist
    attributes:
      label: μ²΄ν¬λ¦¬μ¤νΈ
      options:
        - label: μ›ν¬ν”λ΅μ° νμΌ μ¶”κ°€
        - label: ν…μ¤νΈ ν†µκ³Ό ν™•μΈ
        - label: λΉλ“ μ„±κ³µ ν™•μΈ
